// Public type surface for the FE, sourced from the OpenAPI spec.
//
// The bulk of these types are GENERATED by `pnpm run generate:types` from
// /api-docs/openapi.json into `generated.ts`. This file just re-shapes them
// into flat names (`Artist`, `ArtistInput`, …) so `import type { Artist }
// from '@/api/types'` keeps working everywhere in the codebase.
//
// To regenerate after a Rust model or handler change:
//   1. cargo run                       (in api/, so the spec reflects new code)
//   2. pnpm run generate:types         (in web/)
//


import type { components } from './generated'

type Schemas = components['schemas']

export type Artist = Schemas['Artist']
export type ArtistInput = Schemas['ArtistInput']

export type Artifact = Schemas['Artifact']
export type ArtifactInput = Schemas['ArtifactInput']

export type Tribe = Schemas['Tribe']
export type TribeInput = Schemas['TribeInput']

export type User = Schemas['User']
export type RegisterInput = Schemas['RegisterInput']
export type LoginInput = Schemas['LoginInput']
export type AuthResponse = Schemas['AuthResponse']
export type UserUpdate = Schemas['UserUpdate']

export type Role = Schemas['Role']
